// Generated by the Supabase CLI. Do not edit by hand.
// Regenerate with: pnpm db:types
//
// Populated in Phase 2 once the schema migrations exist. Until then this is an empty but
// structurally valid Database type, so the Supabase clients stay generically typed.

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
